run:
  concurrency: 12
  deadline: 5m
  issues-exit-code: 1
  tests: true
  skip-dirs: []
  skip-dirs-use-default: true
  skip-files:
    - ".*\\.pb\\.go"
    - ".*(.|_)gen\\.go"
  modules-download-mode: vendor
  allow-parallel-runners: true

output:
  format: colored-line-number  # colored-line-number|line-number|json|tab|checkstyle|code-climate
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
    # exclude: .errcheckignore
  goconst:
    min-len: 3
    min-occurrences: 3
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/go-darwin/mach
  golint:
    min-confidence: 0.3
  govet:
    enable-all: true
    check-shadowing: false
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
      - experimental
    settings:
      captLocal:
        paramsOnly: true
      rangeValCopy:
        sizeThreshold: 32
  maligned:
    suggest-new: true
  misspell:
    locale: US
  nakedret:
    max-func-lines: 30
  prealloc:
    simple: true
    range-loops: true
    for-loops: false
  unparam:
    algo: cha
    check-exported: true
  unused:
    check-exported: true

linters:
  enable:
  enable-all: true
  disable:
    - gochecknoglobals
    - gochecknoinits
    - gocyclo
    - gosec
    - lll
    - nakedret
  fast: true

issues:
  exclude-use-default: true
  exclude-rules:
  - linters:
      - golint
    text: "name will be used as mach"
