// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -godefs types_bootstrap.go

package mach

type BoolArrayT = *uint32

type BootstrapPropertyArrayT = *uint32

type BootstrapPropertyT = uint32

type BootstrapStatusArrayT = *int32

type BootstrapStatusT = int32

type CmdT = [512]int8

type NameArrayT = *[128]int8

type NameT = [128]int8

type BootstrapPort = uint32

const BOOTSTRAP_BAD_COUNT = 0x450

const BOOTSTRAP_MAX_CMD_LEN = 0x200

const BOOTSTRAP_MAX_LOOKUP_COUNT = 0x14

const BOOTSTRAP_MAX_NAME_LEN = 0x80

const BOOTSTRAP_NAME_IN_USE = 0x44d

const BOOTSTRAP_NOT_PRIVILEGED = 0x44c

const BOOTSTRAP_NO_CHILDREN = 0x452

const BOOTSTRAP_NO_MEMORY = 0x451

const BOOTSTRAP_SERVICE_ACTIVE = 0x44f

const BOOTSTRAP_STATUS_ACTIVE = 0x1

const BOOTSTRAP_STATUS_INACTIVE = 0x0

const BOOTSTRAP_STATUS_ON_DEMAND = 0x2

const BOOTSTRAP_SUCCESS = 0x0

const BOOTSTRAP_UNKNOWN_SERVICE = 0x44e
