version: 2.1

orbs:
  golang: cci-orb/golang@volatile
  codecov: codecov/codecov@volatile

darwin: &darwin
  executor: golang/macos
  working_directory: ~/go/src/go-darwin.dev/mach

jobs:
  test:
    <<: *darwin
    environment:
      GO111MODULE: "on"
    steps:
      - run:
          name: Show versions
          command: |
            uname -a
            sw_vers
            xcodebuild -version
            system_profiler SPHardwareDataType
      - checkout
      - golang/homebrew
      - golang/gomod:
          file: "go.mod"
          paths: "~/go/pkg/mod"
      - run:
          name: Test and collect coverages
          command: |
            make coverage/ci
      - codecov/upload:
          file: "/tmp/artifacts/coverage.out"
      - store_artifacts:
          path: /tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts
      - store_test_results:
          path: /tmp/test-results

  lint:
    <<: *darwin
    environment:
      GO111MODULE: "on"
    steps:
      - checkout
      - golang/homebrew
      - golang/gomod:
          file: "go.mod"
          paths: "~/go/pkg/mod"
      - run:
          name: Run lint for sources
          command: |
            make lint

workflows:
  version: 2
  workflows:
    jobs:
      - test:
          context: org-global
      - lint:
          context: org-global
