version: 2.1

orbs:
  golang: cci-orb/golang@volatile
  codecov: codecov/codecov@volatile

jobs:
  test:
    macos:
      xcode: 12.5.0
    shell: "/bin/bash --login -e -o pipefail"
    environment:
      PATH: /Users/distiller/go/bin:/usr/local/go/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
      GOPATH: /Users/distiller/go
    resource_class: m2.medium
    working_directory: ~/go/src/go-darwin.dev/mach
    steps:
      - run:
          name: Show versions
          command: |
            uname -a
            sw_vers
            xcodebuild -version
            system_profiler SPHardwareDataType
      - checkout
      - golang/install:
          version: 1.16.3
      - golang/gomod:
          file: "go.mod"
          paths: "~/go/pkg/mod"
      - run:
          name: Test and collect coverages
          command: |
            make coverage/ci
      - codecov/upload:
          file: "/tmp/artifacts/coverage.out"
      - store_artifacts:
          path: /tmp/artifacts
      - store_test_results:
          path: /tmp/test-results

  lint:
    macos:
      xcode: 12.5.0
    shell: "/bin/bash --login -e -o pipefail"
    environment:
      PATH: /Users/distiller/go/bin:/usr/local/go/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
      GOPATH: /Users/distiller/go
    resource_class: m2.medium
    working_directory: ~/go/src/go-darwin.dev/mach
    steps:
      - checkout
      - golang/install:
          version: 1.16.3
      - golang/gomod:
          file: "go.mod"
          paths: "~/go/pkg/mod"
      - run:
          name: Run lint for sources
          command: |
            make lint

workflows:
  version: 2
  workflows:
    jobs:
      - test:
          context: org-global
      - lint:
          context: org-global
