name: Semgrep

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '25 17 * * 1'

jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@main

      - uses: returntocorp/semgrep-action@develop
        with:
          publishToken: ${{ secrets.SEMGREP_APP_TOKEN }}
          publishDeployment: ${{ secrets.SEMGREP_DEPLOYMENT_ID }}
          generateSarif: "1"

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@main
        with:
          sarif_file: semgrep.sarif
        if: always()
