name: Test

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  test:
    runs-on: macos-12

    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18.x

    - name: Checkout
      uses: actions/checkout@v2

    - uses: actions/cache@v2
      with:
        path: |
          ~/go/pkg/mod
          ~/Library/Caches/go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

    - name: Test
      run: go test -v -race ./...

    - name: Coverage
      run: go test -v -covermode=atomic -coverpkg=./... -coverprofile=coverage.out ./...

    - uses: codecov/codecov-action@v2
      with:
        files: ./coverage.out
        fail_ci_if_error: true
